schema_version = "1.0.0"

id = "Smart_File_Path"
name = "SmartFilePath"
version = "1.8.2"
tagline = "Outil de setup des chemins de rendu"
maintainer = "marting.lebrun@gmail.com"
type = "add-on"

blender_version_min = "4.2.2"

license = ["SPDX:GPL-2.0-or-later"]

tags = ["3D View"]
